// <auto-generated />
namespace KFC.RED.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ssoIDattribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ssoIDattribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201903291947299_ssoIDattribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
