// <auto-generated />
namespace KFC.RED.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class winner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(winner));
        
        string IMigrationMetadata.Id
        {
            get { return "201905151831484_winner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
